### ISSUE TITLE
Mediachain metaschema

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#103]
I still think an extractor/GCD schema approach is probably correct. This means we need to come back to some questions:
- what is our common basket of fields? can we use a notion of field type hierarchy where we know e.g. `composer :< author` but do not erase the specialization?
- how are fields marked up for indexer ingestion? needs low-level (string/bytes/etc) to high level (address/coordinates/etc) types
- should the indexer have a "dumb" ingest-everything-raw mode (reads "rawRef", which is likely to be JSON but maybe not)?

**Comment by parkan** [comment]
@autoencoder definitely open to thoughts here, we can work through my previous approach to this if you want

**Comment by denisnazarov** [comment]
tg is @autoencoder :)

**Comment by parkan** [comment]
oops keep forgetting

**Comment by parkan** [comment]
sorry real tg!

**Comment by parkan** [comment]
@autoencoder you had some comments you wanted to leave here, right?

**Comment by autoencoder** [comment]
Preliminary schema in place now. See the schema used by `mediachain.transactor.client.TransactorClient` in [mediachain-client](https://github.com/mediachain/mediachain-client) and its usage by `mediachain.indexer.mc_ingest.ingest_bulk_blockchain` in [mediachain-indexer](https://github.com/mediachain/mediachain-indexer).

At some point we'll tag a version of this schema as one for which we'll maintain future backward compatibility. Putting that tagging off for a little longer for now, until we get a greater variety of data metadata sources hooked up.

A small addition we may make is to auto-ingest all fields detected to be text.

**Comment by parkan** [comment]
Need to revisit this briefly before #131

**Comment by parkan** [comment]
Superseded by PII, schemas are out of scope for this layer
