### ISSUE TITLE
Reuse of existing pieces

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#12]
Umbrella issue to discuss what off-the-shelf parts can be used to implement the RFC.

Paging @bigs

**Comment by parkan** [comment]
~~queue/broker: [kafka](http://kafka.apache.org/)~~
local kv store: [rocksdb](http://rocksdb.org/)
remote kv store (fake ipfs): dynamo, redis, ???
raft: [copycat](https://github.com/atomix/copycat)

**Comment by vyzo** [comment]
I don't think we need what kafka provides. We just need p2p rpcs over sockets with a standard serialization format. Protobufs or thrift seems like better candidates. kafka is also geared for clusters, p2p systems have different behavioral characteristics.

**Comment by parkan** [comment]
you're probably right, kafka is a bit too heavyweight

**Comment by parkan** [comment]
Pretty clear where this is at now
