### ISSUE TITLE
Mediachain system diagram

### ISSUE THREAD

**Issue by denisnazarov** [mediachain/mediachain#125]
While the RFCs go into granular detail, we have no summary or illustration of the shape of the entire system. Would be great to illustrate the relationships between the transactors, readers, writers, indexers journal, chains, HEADs, artefacts, entities, etc.

@parkan @vyzo any advice on what this should look like?

**Comment by denisnazarov** [comment]
Re-reading the blog post [draft](https://docs.google.com/document/d/1ON2NAN3qbyra59ok8zXnyu6BpbJ6I4F3iqywO4DCc-A/edit), there's a clear mental image of the system being painted there, with a concrete example of data from Getty. We should illustrate that.

**Comment by parkan** [comment]
Ok this is really two diagrams, like we discussed on Friday:
- [ ] static example with several Artefact/Entity chains, how they are interconnected, and how they connect to the journal. I attempted to do that here, though photo cuts off much of the board:
  ![ckinm-avaaadajr-1](https://cloud.githubusercontent.com/assets/204986/16015977/4fa7b588-3166-11e6-9b6e-2e22074cea5e.jpg)
  (there are chains in the middle and the corresponding head pointer updates are on the side)
- [x] lifecycle example that shows relationship between transactor network and clients

**Comment by denisnazarov** [comment]
Damn should've got the whole board.

**Comment by denisnazarov** [comment]
Closing in favor of https://github.com/mediachain/mediachain/issues/143
