### ISSUE TITLE
Demo run-through + video

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#130]
Run through basic EoE demo script and record screencast:
- download metadata from Getty by getty id
- import folder
- read back metadata just inserted by returned canonical id
- pull down raw metadata from IPFS
- pull down image from IPFS
- use reverse image search to get canonical id
- use terms to get canonical id

**Comment by denisnazarov** [comment]
Finally published (although without reverse image search in the demo), so gonna close https://blog.mediachain.io/mediachain-developer-update-xii-video-ed-2589452d588e#.ntth99mbo
