### ISSUE TITLE
Import entire 2.2M Getty dataset

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#132]
Run the entire Getty dataset `(RF Creative|Entertainment|Archive) IDs.txt` through the cluster to establish throughput and performance at scale

**Comment by denisnazarov** [comment]
@vyzo can you fill in more details about what we're measuring and hoping to arrive at here?

**Comment by vyzo** [comment]
We want to stress test and establish the performance envelope of the system.
First of all, ingesting a large dataset will put the system under load, which will show us were the creaks are.

From a measurement stand point:
- measure end to end performance for volume ingestion, locate bottlenecks
- establish copycat cluster throughput envelope as a  baseline for any future replacement
- tune dynamo db provisioning, considering cost implications

**Comment by autoencoder** [comment]
For reference, the related Indexer speed measurements task: [#9](https://github.com/mediachain/mediachain-indexer/issues/9).

**Comment by vyzo** [comment]
Some first results with the getty-entertainment data set, using m3.large instances.
- Single client seems capable of doing up to about 30 artefacts/s with dynamo provisioned at 400write/s; sometimes however it only manges some 12 artefacts/s.
- Simple parallelism (with skew in the bucket distribution) achieved aggregate rate of 60writes/s with dynamo provisioned for 750 writes/s

First attempt to 3-level parallelize the getty-archiv set failed with memory and cpu exhaustion, rendering the instance unrechable; more intelligent parallelization scripts are required.

**Comment by vyzo** [comment]
So second round of measurements, with the getty-entertainment dataset and with bug fixes in the ingestion client to avoid duplicate dynamo writes.

The ingestion of 106313 artefacts took 34m7s wall clock time, and generated blocks up to 318464.
This is with 10x parallelization:
- Ingest rate is 52 artefact/s
- Journal rate is 156 writes/s

Dynamo throughput was adjusted from 150 to 750 writes/s during the ingestion in reaction to throttling.

**Comment by vyzo** [comment]
Next round of measurements, with 20x parallelization and dynamo tweaked to 900 writes/s

Ingesting of 106313 getty entertainment artefacts took 22m47s:
- Ingest rate is 77.8 artefacts/s
- Journal rate is 233 writes/s

**Comment by vyzo** [comment]
With 30x parallelism, ingestion takes 12m12s; dynamo was pre-configured at 1200 writes/s (no backoffs observed).
Rates:
- ingest rate is 145 artefacts/s
- Journal rate is 435 writes/s

**Comment by vyzo** [comment]
Another 30x measurement with ingester deduplication fix (reduces entries written but performs same number of rpcs), took 11m40s
- Ingest rate is 152 artefacts/s
- Journal rate is 304 writes/s as the number of entries was reduced by 1/3

**Comment by vyzo** [comment]
With some problems, bug fixes, and copycat update the, imported the getty rf dataset with 561047 artefacts  in 75m40s; ingest rate was 123.6 artefacts/s.

**Comment by vyzo** [comment]
Copycat seems to become unstable at high degrees of parallelism, with eventual failures hosing the client.
Ingesting the full dataset (1089176 artefacts) with 15x parallelism took 180m59.6s, for an ingest rate of 100.3 artefacts/s.

**Comment by vyzo** [comment]
With the stability fixes in #166, we can have 20x ingestion in 101m12.360s; ingestion rate was 179.3 artefact/s
