### ISSUE TITLE
Mediachain adoption metrics/KPIs

### ISSUE THREAD

**Issue by denisnazarov** [mediachain/mediachain#14]
Wanted to throw out some KPIs I'm thinking would be useful for us to track.
- Number of nodes (just our centralized node now)
- Number of canonicals (moma + tate now)
- Number of canonicals with 2+ revisions 
- [punt] Number of images referenced (e.g. CC NYPL works)
- [punt] Number of image fingerprints 
- Number of unique identities contributing
- Number of recognized organization from identities

(The CV stuff is low-priority but we should keep in mind how it hooks into the infrastructure so we can easily layer on reverse image search when we're ready)

**Comment by jessewalden** [comment]
I'd like to propose another KPI, which will be dependent on the outcome of our next planning meeting:
- # of CC licensed images scraped

**Comment by parkan** [comment]
this lives in Lattice now, I think
