### ISSUE TITLE
Use multiaddr for references instead of raw multihashes

### ISSUE THREAD

**Issue by yusefnapora** [mediachain/mediachain#141]
We should be using [multiaddr](https://github.com/jbenet/multiaddr) to "scope" our references, so we can distinguish between our dynamo datastore and IPFS without any out-of-band knowledge.

We can pick an identifier from the unused range for the dynamo store; it won't be resolvable by non-mediachain clients, but that seems fine.

**Comment by yusefnapora** [comment]
I actually started on a scala multiaddr implementation about six weeks or so ago, but stashed it because it wasn't immediately needed.  I looked through this morning, and I'd say it needs a few hours of work to finish, plus a little bit of testing.  

Refactoring the transactor and client to use the multiaddrs is probably the more challenging part, but I think it's worth doing, since the ipfs vs dynamo confusion is already pretty annoying and hard to coordinate.

I'm going to try to carve out some time this week to finish up the scala multiaddr code, and we can talk more about integration.

**Comment by parkan** [comment]
Can you pop open a PR w/the work to date?

**Comment by yusefnapora** [comment]
sure; I put it in the scala-multihash project, but it should maybe live in its own project: https://github.com/mediachain/scala-multihash/pull/3

**Comment by yusefnapora** [comment]
It occurred to me last night that our immediate use case for multiaddr doesn't really need to involve the transactor at all.  Since the only things we're storing in ipfs at the moment are things referenced in the `meta` map (and thus opaque to the transactor), we could use multiaddr for those on the client side, and hold off on the transactor side for now.

The [py-multiaddr lib](https://github.com/sbuss/py-multiaddr) looks quite good, and it exposes a hook to add your own protocols, so we wouldn't need to change the library to add our own "testnet datastore" protocol.

Just a thought 😄

**Comment by vyzo** [comment]
This is definitely preferable, as it wouldn't require any surgery in the transactor.

**Comment by yusefnapora** [comment]
I did a little experimenting with the py-multiaddr lib earlier today.

While you can add new protocols without changing the library source code (with a little bit of effort), you can't add new "codecs" for parsing the string and byte representations.

So the only thing we can really add without forking the lib is a "marker protocol" that has no address component.  Which would result in a multiaddr like `/mchain/ipfs/QmZUxo3nDiuiBsGzWmnfpADcQGNxwp9gHNSCPk2BH3rwPK`

That works, because there's no address to parse, so no special handling is needed. We could then check for the presence of the `mchain` marker protocol and fetch from the rpc datastore if it's present (using the multihash from the `ipfs` component).

That seems like too much hassle for negligible benefit.  It would still likely break compatibility with anything else that uses multiaddr because of the unknown protocol.  

One thing we could do is use real multiaddrs for ipfs links, and strings like e.g. `/mchain/QmFoo` for our datastore.   Then at lookup time we parse the string if multiaddr decoding fails.  The benefit over just using strings for both is that when we do switch to using IPLD for everything, the multiaddrs will correctly resolve, so that code will eventually come in handy.

@parkan, do you think it's worth doing the "multiaddr with string fallback" thing, or should we give up on multiaddr for now?

**Comment by parkan** [comment]
This seems hacky and annoying. Let's leave it be for now, maybe open an issue on the parent project suggesting support for generic protocols where it just gives you back a bytestring

**Comment by yusefnapora** [comment]
cool, sounds good to me
