### ISSUE TITLE
Data schema diagram

### ISSUE THREAD

**Issue by denisnazarov** [mediachain/mediachain#143]
static example with several Artefact/Entity chains, how they are interconnected, and how they connect to the journal. @parkan  attempted to do that here, though photo cuts off much of the board:
![ckinm-avaaadajr-1](https://cloud.githubusercontent.com/assets/204986/16015977/4fa7b588-3166-11e6-9b6e-2e22074cea5e.jpg)
(there are chains in the middle and the corresponding head pointer updates are on the side)

Related #5 #135

**Comment by denisnazarov** [comment]
Lets stick somewhere in the repo?

**Comment by parkan** [comment]
https://github.com/mediachain/mediachain/issues/5
