### ISSUE TITLE
Testnet metrics/analytics

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#144]
We need to instrument the testnet to measure/detect usage and deal with potential abuse
- [ ] current block height/block explorer
- [ ] web interface to view arbitrary dynamo mhashes
- [x] total # of indexed artefacts/entities
- [x] alerts on S3 fill level, Dynamo throughput, machine health
- what else?

**Comment by vyzo** [comment]
We also need to think about code instrumentation for collecting metrics we can monitor and alert on.

**Comment by parkan** [comment]
@vyzo reading through these, let's add a block height and an object count gauge

**Comment by vyzo** [comment]
Ok, I will add a counter for canonical record writes and track the index of the returned entry with a gauge; the latter will give us the block height.

**Comment by vyzo** [comment]
#172 adds the relevant metrics

**Comment by parkan** [comment]
Sweet. Gonna close this, the dynamo thing is optional
