### ISSUE TITLE
Testnet nuke tooling

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#145]
Need tools to nuke + reinitialize testnet

**Comment by parkan** [comment]
Ok having dealt with trying to ingest a bunch of records with changing formats into indexer, I would say this is _high priority_

@vyzo: what's a good way to wipe transactors? can we make a tool to do it?

**Comment by vyzo** [comment]
For the transactor you need the following:
- shutdown the journal servers
- clean up /mnt/transactor/\* state
- restart the journal servers in some order, building a cluster.

In addition we would like to wipe the dynamo tables and perhaps the S3 backups. 

Tooling could come in the form of ansible playbooks for setting up and tearing down a testnet with a simple command.

**Comment by parkan** [comment]
Sounds good, let's do this

**Comment by vyzo** [comment]
Added unified service script for starting/stopping the transactor services in #155

**Comment by vyzo** [comment]
tip of #155 also adds playbooks to start and kill/wipe the testnet

**Comment by vyzo** [comment]
#155 has been merged in, providing the necessary tooling; closing.
