### ISSUE TITLE
Public testnet documentation/blog post

### ISSUE THREAD

**Issue by denisnazarov** [mediachain/mediachain#148]
- [x] Repo document for using testnet
- [x] Blog post

@parkan would this be a text document of the steps from the video

**Comment by denisnazarov** [comment]
Can we add some more thorough checklists here. @yusefnapora did a great job on the corresponding https://github.com/mediachain/mediachain-client/issues/30

**Comment by parkan** [comment]
Sure, go for it

**Comment by parkan** [comment]
@bigs want to pick this up

**Comment by bigs** [comment]
@parkan sure

**Comment by jessewalden** [comment]
@bigs @parkan just came back here per Denis' https://github.com/mediachainlabs/internal/issues/1 _ would be great have a clear plan for finalizing/publishing documents that aligns with MIT and separately, testnet launch milestone
