### ISSUE TITLE
Public Datastore Interface

### ISSUE THREAD

**Issue by vyzo** [mediachain/mediachain#150]
Implement a new RPC service that provides access to the Dynamo Datastore, with a simple put/get interface.
This is necessary for a functional public testnet prior to the deployment of IPLD.

**Comment by parkan** [comment]
So, I wonder, is it so bad to distribute an IAM role that only has tightly scoped GET and PUT? I guess people could extract it and flood our datastore w/another tool in theory, but would definitely be easy to implement

**Comment by vyzo** [comment]
#154 provides an implementation as an RPC service so that we have an endpoint and interface we control without granting direct access to dynamo.
