### ISSUE TITLE
Tag release for public testnet

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#152]
We should start observing a versioned release schedule, particularly to keep our grpc-speaking tools in sync.
- [x] bump sbt project version to 0.1
- [ ] git tag as v0.1
- [x] _[OPTIONAL]_ use something like https://github.com/sbt/sbt-git to sync tags + sbt versions
- [ ] specify corresponding tag in https://github.com/mediachain/mediachain/issues/152

**Comment by parkan** [comment]
@yusefnapora I think you did some/all of these, can you check off as appropriate?

**Comment by yusefnapora** [comment]
Sure.  I haven't actually tagged a v0.1 release yet.  Should we tag the current master as v0.1.0?

**Comment by parkan** [comment]
do you want to try the release branch approach?

**Comment by parkan** [comment]
(so basically feature cut right now but don't tag yet, branch can exist as living RC so last minute fixes can go in -> tag tomorrow)

**Comment by vyzo** [comment]
We probably want to bump the scala grpc dependency as well? 
It's still at 0.14 -versus whatever we currently have in the client.

**Comment by yusefnapora** [comment]
oh good call.  grpc-java was still at 0.14 last I checked, but it just got bumped to 0.15 a week ago.
