### ISSUE TITLE
Add tasks for Transactor milestone

### ISSUE THREAD

**Issue by bigs** [mediachain/mediachain#16]
Kicking off transactor design. There are two major surfaces of the transactor interfaces:
- Staging Transactions
  - Point of interaction for clients
- Journal syndication
  - API used by clients--push or pull

We want to focus on interface driven design, allowing us to fake as many things as possible. These include:
- Journal persistence
  - In memory, array/linked list based (our approach for now)
  - RocksDB
  - IPFS
  - Cassandra, etc
- Consensus
  - We should aim to wrap Raft in a layer more domain (journal) specific, so we can tolerate "unity" i.e. single node consensus (ht @parkan) 
- Syndication
  - Push/pull whatever

**Comment by bigs** [comment]
Are there any interfaces missing here?

**Comment by vyzo** [comment]
we also need to consider health checking and dealing with crashes.

**Comment by vyzo** [comment]
We can start by describing the PhaseII development milstone:
A few tier-1 nodes (transactors) in a fully connected graph effectively providing data write services. 
Then we can isolate parts, both at the interface level but also at the component/process level.

So to start we need
- basic overlay maintenance with simplified transaction commit
- client API and stub implementation
- store interface and stub implementation

**Comment by parkan** [comment]
I think this is missing the `Peer API` (EDIT: or wait is that what you mean by "API used by clients"? what I mean is the thing that L-SPACE hooks into)

**Comment by vyzo** [comment]
right, I mean the Client in RFC2 nomenclature -- L-SPACE will be a client of the core network.
Do we want a separate repo for the core network, or do we want to build in L-SPACE with a separate package?

**Comment by vyzo** [comment]
So, in terms of implementation as a replicated state machine (eg with copycat), the transactor network effectively maintains the blockchain index.

The responsibilities of the transactor:
- maintain canonical -> chain head index
- accept a sequence of Entities/Artefact/Cells for a store write / blockchain commit
- perform a replicated write which updates the index and atomically writes to the store
- collect the operations in a current block
- every X transactions or Y minutes write the block, extend the blockchain and atomically write a new store to the store

Using copycat with an in memory index and binary index snapshots to disk, we can scale up to the RAM of our node cloud instances. If we go for something small and inexpensive we can say have 1G of RAM for the index, so we can effectively scale up to about 10 mil entries.

In terms of the final Phase II/Transactor network milestone we should consider writing the seed data and constructing the Genesis blockchain.

**Comment by vyzo** [comment]
The atomicity of datastore needs some elaboration.
The transactors can race to either write or pin the data to the store. Because the index is maintained consistent by the state machine, the representation of the data in the store is deterministic. In effect the "atomic write to the store" is a "write or pin".

One important detail, in regards to persistence in the store, is that we need to pin all cells in the various chains recorded in the blockchain, not just the heads.
The pinning can serve from disk and not in-memory, with a scaling limit at the size of the blockchain. With cheap cloud instances we should be able to scale up to ~20G for the blockchain.

**Comment by vyzo** [comment]
Another point: Given the index any node can recover all chain cells by walking backwards from chain heads, provided they are already pinned by other nodes.

Also, we should have a separate component for the store, with the transactors interacting through an rpc interface.
The store would handle journal persistence and write/pinning for objects in the chain and could handle the blockchain as well.
In addition, the decomposition allows us to mock the store, either with a key-value store db or dynamodb etc.
Let's put it in a separate process/box from the transactors, and let's limit the latter to a replicated state machine maintaining the index.

**Comment by parkan** [comment]
My assumption so far was that this repo would hold the core network code (I already made an sbt multiproject with a few stub projects, see the top level)

re: journal persistence, do you mean writing to _local FS_ on the node, or to IPFS?

**Comment by vyzo** [comment]
I mean writing to the datastore -- we can do various forms of persistence if we have an external component: local key-value for testing, dynamodb for bootstrap, and ipfs for when we go live. 
We can actually use dynamodb for backing store (instead of S3) even when we are writing to ipfs.

**Comment by parkan** [comment]
Ok, sounds good. So the initial implementation will be no-op, presumably. Agreed on separation then.

**Comment by bigs** [comment]
@parkan to be clear this was just for transactor design

**Comment by parkan** [comment]
@bigs I've made individual tasks for these and mostly assigned them to you (other than the ones I know vyzo is working on). Please [take a look](https://github.com/mediachain/mediachain/milestones/Transactor%20Design) and make sure they're correct/reassign + close this issue 😄
