### ISSUE TITLE
Spin up testnet/devnet

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#167]
The current "devnet" can become the testnet (and we spin up a new devnet), or a new testnet should be spun up

**Comment by vyzo** [comment]
Let's keep the current boxes as devnet and spin up a new testnet; we can then assign the facade ip to the new rpc server.

**Comment by vyzo** [comment]
Spun up 4 new instances for the testnet, will seed it with the getty dataset and then re-assign the facade ip to the rpc server.

**Comment by vyzo** [comment]
Ingested getty dataset and reset the facade IP to point to the testnet rpc service.
