### ISSUE TITLE
Create hostname + open firewall

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#168]
- [x] Create a hostname for transactor facade
- [x] Open firewall for public writes to transactor facade + datastore (devnet)
- [x] Point facade IP to new testnet rpc service (#167)

**Comment by jessewalden** [comment]
let me know specifics on what i need to do?

**Comment by parkan** [comment]
You should assign `52.7.126.237` as `facade.mediachain.io`

**Comment by jessewalden** [comment]
done

**Comment by parkan** [comment]
Should we open actual transactors too or just the facade?

**Comment by vyzo** [comment]
We only need to open up the rpc server, which is already open btw.

@parkan  the current elastic ip assignment for 52.7.126.237 does not point to the rpc server; you pointed to the old test-box.

**Comment by vyzo** [comment]
I re-associated the elastic IP with the rpc server in the current devnet; will point to the testnet rpc server once the new testnet is up (#167).

**Comment by vyzo** [comment]
Associated IP with the testnet rpc server.

**Comment by vyzo** [comment]
A record for facade.mediachain.io resolves now; closing.

**Comment by parkan** [comment]
Cool, I see you renamed some machines, too. Looks good to me.

Ended up using this to sync the names to my /etc/hosts: https://www.npmjs.com/package/ec2sync
