### ISSUE TITLE
Transactor interface description

### ISSUE THREAD

**Issue by yusefnapora** [mediachain/mediachain#17]
This is subject to change as we hash things out :)
# Transactor interfaces

The Transactor peer nodes are responsible for writing data to the system
and ensuring consistency.  

Transactors have two main client-facing interfaces:
- writing data to persistent storage (e.g. IPFS) on behalf of clients
- informing clients of changes to the Journal when updates are made

As well as "internal" responsibilities:
- maintaining the chain of updates for metadata entries
- communication with other transactor nodes to achieve consensus
## Writing data

The transactor accepts data in the format described by [RFC-1](https://github.com/mediachain/mediachain/blob/master/rfc/mediachain-rfc-1.md), with the
important exception that the `chain` field for the various `ChainCell`s is not
filled in by the client.

Since non-Transactor peers do not participate in the consensus process, they
cannot know with certainty whether their pointer to the head of a given chain
will still be correct when the transaction is committed and written to the
Journal.  

[RFC-2](https://github.com/mediachain/mediachain/blob/master/rfc/mediachain-rfc-2.md) describes a strategy for resolving conflicting updates with
"merge" cells that resolve forks into a single chain while preserving the 
data from both forks.  

In the short term, our plan is for client nodes to defer the "chaining" of
updates to the Transactor peers.  A client will therefore submit updates
with all information except the `chain` field, which will be determined by
the Transactor when the update is committed.

This has implications for signing, in that the `chain` field will need to be
omitted when verifying signatures for a cell, as it is unavailable to the client
when signing.
### Data types and services

There are two fundamental write operations that clients can submit:
- creation of a new Canonical metadata entry (`Entity` or `Artefact`)
- updates to an existing entry

In both cases, RPC messages are sent to a service endpoint requesting that the
data be added to the system.  The format of the messages should track closely
to that described in [RFC-1](https://github.com/mediachain/mediachain/blob/master/rfc/mediachain-rfc-1.md). 

The server will respond synchronously with either an "acknowledgement" response,
or a validation error if the message cannot be parsed or otherwise fails an 
initial validation pass.  

Importantly, the initial validation does not ensure that the data is guaranteed 
to be accepted, only that it is consistent with the expected format, and that it
has no "dangling references", etc.  For example, attempting to issue an update
to a non-existent `Artefact` would immediately fail.  Other causes of validation
failure might include failing to conform to an expected schema (an invalid 
`timestamp` format, for example), or trying to submit an `EntityUpdateCell` that
refers to an `Artefact` instead of an `Entity`.

In other words, initial validation only covers what can be known at the 
immediate time of submission.  However, since the block consensus protocol for
confirming a transaction may take an indeterminate amount of time, it is
undesirable to "block" the connection until confirmation occurs.  Instead, the
transactor returns an immediate validation response, and the client must track
journal updates to confirm that the data was written successfully.  

Alternatively, the acknowledgement response could include a unique token that
identifies the write request.  When the transaction completes (successfully or
otherwise), the Transactor can send a message to the client with the status and
include the token.  The client can then either mark the transaction as 
successful, or retry on failure if possible.

**Comment by yusefnapora** [comment]
Thinking more about how this diverges from the RFC... omitting the `chain` field from the client's submission removes an important piece of information, which is the state of the chain as it existed from the client's point of view at the time of submission... in other words, without the `chain` field, you can't tell what state the client _thought_ the chain was in when they submitted...

**Comment by vyzo** [comment]
The .chain field should be present in client requrests:
it can point to nil to indicate a cons anywhere request or it can point to an extant chain pointer, in which case the transactor can verify that it points to the current chain head or reject it immediately if this isn't the case.

**Comment by vyzo** [comment]
We also need to consider the signatures -- which parts of the message are signed? Is the signature coming from the client, or is the transactor front-end signing with its own key, or perhaps both?

**Comment by vyzo** [comment]
Fundamentally, I think we have 3 operations if we treat the transactor network as a replicated index:
- Insert, which inserts an artefact or entity to the store; returns a canonical for the object
- Update, which conses a new cell to the chain for a canonical; returns the canonical for the new chain head
- Get, which retrieves the chain head for a canonical; the client can then retrieve the entire chain from the store independent of the transactors

The store lives independently of the transactor and offers a put/get interface to clients.

**Comment by vyzo** [comment]
The second part of the service that the transactor network provides is notifications for inserts and updates.
This is a major use case -- e.g. services that index on metadata  need to be notified when new artefacts and entities are inserted or when a chain head changes

**Comment by parkan** [comment]
I think the "notifications for inserts and updates" part is covered by "journal syndication" here: https://github.com/mediachain/mediachain/issues/16

**Comment by vyzo** [comment]
Yes, indeed. I am just pointing out that it is an important part of the service, so we should give it proper reference in the interface description.

**Comment by bigs** [comment]
some sketches of interfaces (paging @vyzo)

``` scala
/** A generic interface to the chain cell
  */
abstract class ChainCell(/* ... */)

/** An interface to the chain's backing store
  */
trait ChainNode {
  def cell(): ChainCell
  def previous(): Option[ChainNode]
}

abstract class JournalEntry {
  def cell(): ChainCell
}

/** Interface for journal writing/access
  */
trait Journal {
  def head(): JournalEntry

  def commit(entry: Entry): Xor[JournalError, JournalEntry]
}

/** Interface for syndicating updates to the journal
  */
trait Peer {
  def updateJournalHead(head: JournalEntry): Option[PeerError]
}

type PeerRegistry = Iterable[Peer]
```

**Comment by vyzo** [comment]
So why are we not modelling the block chain as a sequence of blocks?
Is the Journal your approach in modelling the blockchain or is this the transactor-client interface?

We should have insert,update, and get as basic interface + a way to register a callback to a Client (you call it Peer).

**Comment by vyzo** [comment]
Also, we need to model Artefacts and Entities somewhere in the interface given how we plan the transactor doing the writes.

**Comment by bigs** [comment]
@vyzo totally. i think we may have just gotten a bit mixed up w/ the layers of abstraction i'd added. @parkan pointed out i had one confusing/unnecessary layer in there, so i've removed it.

additionally, these abstractions are for use in the implementation of more abstract transactor logic. the holes i don't intend to fill right now are artefacts and entities (since they will likely be trivial case class impls) as well as RPC interfaces for things like registering peers.

``` scala
/** A generic interface to the chain cell
  *
  * Since the cdr of the chain can be nil, we use `Option`
  */
abstract class ChainCell {
  def chain(): Option[ChainCell]
}

/** A generic interface to the journal entry, allowing for traversal of its own.
  *
  * Since the cdr of the journal can be nil, we use `Option`
  */
abstract class JournalEntry {
  def cell(): ChainCell
  def chain(): Option[JournalEntry]
}

/** Interface for journal writing/access
  */
trait Journal {
  def head(): JournalEntry
  def commit(entry: Entry): Xor[JournalError, JournalEntry]
}

/** Interface for syndicating updates to the journal
  */
trait Peer {
  def updateJournalHead(head: JournalEntry): Option[PeerError]
}

type PeerRegistry = Seq[Peer]
```

**Comment by bigs** [comment]
another thought: maybe we could use the terminology "transactor" and "clients"--best of both worlds. i realized that since this is a p2p network there are many coalitions of "peers" which can be confusing.

**Comment by vyzo** [comment]
yeah, let's call them transactors and clients.

In the model, you are missing support for inserts, which add Artefacts and Entities to the store.
They still have a JournalEntry, but they don't have a chain as they are the elements to which chains refer.

**Comment by vyzo** [comment]
So, working a bit in the Model. I think we want to pretty much model the rfc datatypes for the store and provide the transactor/client interface. 
Something along these lines:

``` scala
object Model {
  // Mediachain Datastore Records
  abstract class Record

  // Canonical References to records
  abstract class Reference

  // Canonical Records: Entities and Artefacts
  abstract class CanonicalRecord extends Record
  case class Entity extends CanonicalRecord
  case class Artefact extends CanonicalRecord

  // Chain Records: chain cells for entities and artefacts
  abstract class ChainCell extends Record
  abstract class EntityChainCell extends ChainCell
  abstract class ArtefactChainCell extends ChainCell
  // chain cell types ...

  // Journal Entries
  abstract class JournalEntry
  case class CanonicalEntry extends JournalEntry
  case class ChainEntry extends JournalEntry

  // The Journal as a datatype
  trait Journal {
    def head: JournalEntry
    def rest: Option[Journal]
  }

  // the Journal Index transactor interface
  trait JournalIndex {
    def insert(rec: CanonicalRecord): Xor[JournalError, CanonicalEntry]
    def update(ref: Reference, cell: ChainCell): Xor[JournalError, ChainEntry]
    def lookup(ref: Reference) : Option[Reference]
  }

  trait JournalClient {
    def updateJournal(entry: JournalEntry): Unit
  }
}
```

**Comment by vyzo** [comment]
A different approach with the Journal Interface is to model the blockchain directly: 

``` scala
  abstract class JournalBlock {
    def index: BigInt
    def chain: Reference
    def entries: Seq[JournalEntry]
  }

  trait Journal {
    def insert(rec: CanonicalRecord): Xor[JournalError, CanonicalEntry]
    def update(ref: Reference, cell: ChainCell): Xor[JournalError, ChainEntry]
    def lookup(ref: Reference) : Option[Reference]
    def currentBlock: JournalBlock
  }

  trait JournalClient {
    def updateJournal(entry: JournalEntry): Unit
    def commitJournalBlock(index: BigInt, ref: Reference): Unit
  }
```

This transactor interface (now called Journal instead of JournalIndex) provides read access to the current block being generated.
This allows clients to bootstrap by requesting the current block from the transactor, and fetching previous blocks from the store while receiving updates through the JournalClient interface.

**Comment by vyzo** [comment]
We also need to model the datastore in order to be able to implement the transactor. A simple put/get interface should be sufficient:

``` scala
  trait Datastore {
    def get(ref: Reference): Xor[DatastoreError, IPLDObject]
    def put(data: IPLDObject): Xor[DatastoreError, Reference]
  }
```
