### ISSUE TITLE
gRPC error metadata

### ISSUE THREAD

**Issue by yusefnapora** [mediachain/mediachain#189]
Since we updated to grpc 0.15.0 a little bit ago, we can now add custom gRPC `Metadata` to our `StatusRuntimeException`s when we throw an error in the RPC service.  This will let us ditch the horrible error string parsing hack in the client that pulls the multihash ref out of duplicate insert errors.

  gRPC `Metadata` is basically a list of key-value pairs, which allows multiple values for the same key.  Keys need to be ascii and follow HTTP header name rules.  Values can be either ASCII strings or byte arrays, and you can provide your own `BinaryMarshaller` to pack / unpack your types to byte arrays.

Should we use cbor for the values, or would a more human-readable encoding (like UTF-8 JSON) be better?  I think cbor is probably fine, since we'll need to write some code to extract the metadata from the error in the first place, and we can slip the cbor decoder in there.

TODO:
- [x] attach the metadata in `TransactorService` when we throw
- [x] update the python client to decode the metadata

**Comment by parkan** [comment]
Do you mean CBOR the multihashes and actual cells, or messages themselves? I think we should consistently CBOR objects that get written to the blockchain, but messages should just be protobuf.

**Comment by yusefnapora** [comment]
I just mean the error metadata.  Like ideally, you'd be able to get something like this if you receive a `JournalDuplicateError`:

``` json
{
 "errorType": "DuplicateInsert",
 "ref": "QmF00..."
}
```

But we have to pack that into a byte array somehow to attach it to the grpc `Metadata` that accompanies the error.  Json strings would be fine, and probably more readable if you happen to dump the metadata to the console or see it in a debugger or something.

**Comment by parkan** [comment]
Glancing at the go docs (the java ones aren't as complete), it seems like we should be able to just marshall a `Map[String, Serializable]`?

**Comment by parkan** [comment]
Ok I see the [java docs](http://www.grpc.io/grpc-java/javadoc/io/grpc/Metadata.html) now, this is annoying java-ish (again), but it seems like we can just pass everything down as string -> string fields, except e.g. multihashes which get binary marshaller and a special `-bin` suffix for keys.

**Comment by yusefnapora** [comment]
yeah, that's a good point.  we can just put e.g. `mediachain-error-type` into a string field.

For some reason I was thinking about packing a whole error structure into a single field, but I like your way better :)

We could use base58 for the multihashes and skip the binary marshaller.

**Comment by parkan** [comment]
Yeah, good call on just base58ing it -- performance overheads don't matter that much for errors.

**Comment by vyzo** [comment]
Yeah, passing meta will certainly help clean up our errors. 
There is real performance overhead with passing the base58 string, as we already return it in an ugly stringified form.

**Comment by yusefnapora** [comment]
if you've noticed a performance hit from the existing error messages, then let's just use the binary multihash with the default `BinaryMarshaller`.   We do end up with a lot of `JournalDuplicateError`s when doing the bulk ingestions, since we're using that to deduplicate identical records.
