### ISSUE TITLE
User stories

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#201]
Not sure where to best put this, sticking in here for now. Starting with an old favorite example:
### CASE: NYPL + OldNYC
- NYPL publishes their public domain (?) collection to `$nypl` using their IDs
- OldNYC publishes their data to `$oldnyc` using their own IDs, as well as the parent NYPL UUIDs
- DPLA publishes a translated (normalized) version of NYPL's data into `$dpla`
- I can now query `[$dpla, $oldnyc]` and get records enriched with geocoding data from OldNYC!

NYPL record

```
[nypl_510d47e2-c33f-a3d9-e040-e00a18064a99] -> {"nyplAPI":{"request":{"uuid":{"$":"510d47dd-05f4-a3d9-e040-e00a18064a99"},"request":{"uuid":{"$":"510d47dd-05f4-a3d9-e040-e00a18064a99"},"perPage":{"$":"10"},"page":{"$":"1"},"totalPages":{"$":"1"}}},"response":{"headers":{"status":{"$":"success"},"code":{"$":"200"},"message":{"$":"ok"}},"mods":{"version":"3.4","schemaLocation":"http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/v3/mods-3-4.xsd","titleInfo":{"lang":"eng","supplied":"no","usage":"primary","title":{"$":"Manhattan: 42nd Street - Park Avenue"}},"typeOfResource":{"$":"still image"},"genre":{"authority":"lctgm","valueURI":"http://id.loc.gov/vocabulary/graphicMaterials/tgm007721","$":"Photographs"},"originInfo":{"dateCreated":{"encoding":"w3cdtf","keyDate":"yes","$":"1916"}},"subject":[{"geographic":{"authority":"naf","$":"New York (N.Y.)"}},{"geographic":{"authority":"lcsh","$":"Manhattan (New York, N.Y.)"}},{"topic":{"authority":"lctgm","$":"Automobiles"}}],"identifier":[{"displayLabel":"Hades Collection Guide ID (legacy)","type":"local_hades_collection","$":"219"},{"displayLabel":"NYPL catalog ID (B-number)","type":"local_bnumber","$":"b19806373"},{"displayLabel":"Hades struc ID (legacy)","type":"local_hades","$":"402767"},{"type":"uuid","$":"eb938540-c542-012f-a518-58d385a7bc34"}],"location":[{"physicalLocation":[{"authority":"marcorg","type":"repository","$":"nn"},{"type":"division","$":"Irma and Paul Milstein Division of United States History, Local History and Genealogy"},{"type":"division_short_name","$":"Milstein Division"},{"type":"code","$":"LHG"}],"shelfLocator":{"$":"AZ 12-2335"}},{"physicalLocation":[{"type":"division","$":"Irma and Paul Milstein Division of United States History, Local History and Genealogy"},{"type":"division_short_name","$":"Milstein Division"},{"type":"code","$":"LHG"}]}],"note":{"type":"citation/reference","$":"0532-C5"},"relatedItem":{"type":"host","titleInfo":{"title":{"$":"Manhattan"}},"identifier":[{"type":"uuid","$":"eff822e0-c539-012f-95fa-58d385a7bc34"},{"type":"local_hades","$":"359227"}],"relatedItem":{"type":"host","titleInfo":{"title":{"$":"Photographic views of New York City, 1870's-1970's, from the collections of the New York Public Library"}},"identifier":[{"type":"uuid","$":"a301da20-c52e-012f-cc55-58d385a7bc34"},{"type":"local_hades","$":"359206 local_hades_collection"}]}}},"numResults":{"$":"2"},"capture":[{"uuid":{"$":"510d47dd-05f4-a3d9-e040-e00a18064a99"},"apiUri":{"$":"http://api.repo.nypl.org/api/v1/items/mods/510d47dd-05f4-a3d9-e040-e00a18064a99"},"typeOfResource":{"$":"still image"},"imageID":{"$":"712969F"},"sortString":{"$":"0000000001|0000000003|0000005507|0000000001"},"itemLink":{"$":"http://digitalcollections.nypl.org/items/510d47dd-05f4-a3d9-e040-e00a18064a99"},"orderInSequence":{"$":"1"},"isPartOfSequence":{"$":"true"},"totalInSequence":{"$":"2"},"title":{"$":"Manhattan: 42nd Street - Park Avenue"},"rightsStatement":{"$":"The New York Public Library is interested in learning more about items you've seen on our websites or elsewhere online. If you have any more information about an item or its copyright status, we want to hear from you. Please contact DigitalCollections@nypl.org with your contact information and a link to the relevant content."}},{"uuid":{"$":"510d47dd-05f3-a3d9-e040-e00a18064a99"},"apiUri":{"$":"http://api.repo.nypl.org/api/v1/items/mods/510d47dd-05f3-a3d9-e040-e00a18064a99"},"typeOfResource":{"$":"still image"},"imageID":{"$":"712969B"},"sortString":{"$":"0000000001|0000000003|0000005507|0000000002"},"itemLink":{"$":"http://digitalcollections.nypl.org/items/510d47dd-05f3-a3d9-e040-e00a18064a99"},"orderInSequence":{"$":"2"},"isPartOfSequence":{"$":"true"},"totalInSequence":{"$":"2"},"title":{"$":"Manhattan: 42nd Street - Park Avenue"},"rightsStatement":{"$":"The New York Public Library is interested in learning more about items you've seen on our websites or elsewhere online. If you have any more information about an item or its copyright status, we want to hear from you. Please contact DigitalCollections@nypl.org with your contact information and a link to the relevant content."}}]}}}
```

OldNYC record

```
[nypl_510d47e2-c33f-a3d9-e040-e00a18064a99, oldnyc_712969f ] -> { "coords": "40.752150,-73.977773" }
```

DPLA record:

```
[nypl_510d47e2-c33f-a3d9-e040-e00a18064a99, dpla_417af65e13c60f6fec48426d0a36f303 ] -> ...
```

**Comment by jessewalden** [comment]
How does OldNYC discover NYPL's IDs?
Does Content ID fit in this story?

**Comment by parkan** [comment]
@jessewalden at this point it's a derivative/composite data set, so we don't need content ID. They already essentially do this, though I glossed over this detail to make the example more illustrative. Any oldnyc ID (e.g. 721265f-a in https://www.oldnyc.org/#721265f-a) is also an NYPL ID.

Totally open to coming up with a similar example that does use Content ID/CV, though -- maybe something based on the ukiyo-e project?

**Comment by parkan** [comment]
### CASE: CC Photos
- Some proactive orgs (e.g. Flickr, Wikimedia) publish metadata about photos in their collections to their respective namespaces, under their own IDs
- CC uses filtered aggregation to pull in CC content from `$flickr`, `$wikimedia`, etc into `$cc`
- Other orgs (e.g. unsplash) do not publish metadata to mediachain at all, but have an API or lenient scraping policy. A 3rd party (let's call them "CCImageHound") can scrape or consume the APIs and emit statements into `$ccimagehound` under original ids, e.g. `unsplash:jIdKrtJF8Uk`
- CC can choose to include the `$ccimagehound` stream in `$cc`, or the two can be aggregated
- Even if some statements from `$ccimagehound` overlap statements in `$cc` (because an org has an API and a mediachain node, for example), they are idempotent and no logical duplication occurs

**Comment by denisnazarov** [comment]
Awesome issue! 👍

**Comment by jessewalden** [comment]
## Writing

- Creative Commons (@yusefnapora) 
 - Wants to create an 'open ledger' composite of ALL CC works
 - Wants to maintain the index and decide who can contribute to it directly
 - Wants to use this index to build useful products, like search and analytics 

- Individual Creator 
  - Wants to register an image through a UI powered by Mediachain API
  - Wants to track usage of their image

- Developer at OldNYC
  - Wants to extend NYPL data
  - Wants to contribute to NYPL dataset to aid discovery, and make data extendable

- Technology Strategist at Metropolitan Museum (Neal)
  - Wants to publish their open data in space that other likeminded peers participate in
  - Wants to track usage of their data
  - Wants to be able to easily ingest related data

- CTO at Getty Images
 - Wants to enable more non-commercial use of their images
 - Wants to track analytics on use of those images (privately?)
 - Wants attribution to be automated when images are re-used

- Developer at Archillect
  TK- @denisnazarov 

## Reading

- Individual Consumer
  - Wants to reverse lookup an image to find information about it through a UI powered by Mediachain API

- Developer at Medium:
  - Wants to access to all CC images in Mediachain
  - Wants to automate attribution for those images
  - Wants to ping back the network about usage on Medium

**Comment by parkan** [comment]
@jessewalden good list, though I think it's important to consider complete lifecycles, rather than individual inputs/outputs, because the data isn't fungible (for ex. OldNYC isn't interested in individual contributor's artworks) -- the challenge is to find **matching** read cases for the writes.

**Comment by jessewalden** [comment]
@parkan re: https://github.com/mediachain/mediachain/issues/201#issuecomment-243238071

taken as a whole, the individual input/output use cases give us a whole lifecycle. keeping them separate for now makes it a little easier to reason about the priority of each participant's primary wants/incentives for participation.

**Comment by parkan** [comment]
@jessewalden this is how we've been thinking about these the whole time, though -- which has resulted in a lot of gaps. Breaking down to individual users makes sense while developing specific tooling and messaging, but these pieces are only meaningful in the context of paths or cycles of creation and consumption. Think of it in terms of the [food web](https://en.wikipedia.org/wiki/Food_web): if a consumer cannot find the kind of information it wants to consume, it will not thrive, no matter how well adapted the environment is to their needs otherwise, nor will a producer with no consumer be healthy. More importantly, this kind of analysis can identify the relative importance of ecosystem components: which are the "keystone species" and which merely augment an already filled niche.
