### ISSUE TITLE
Copycat state machine

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#22]
Base state machine on top of https://github.com/atomix/copycat

partial implementation in https://github.com/mediachain/mediachain/pull/21/

**Comment by vyzo** [comment]
Merged in the first implementation: The state machine computes the index of the mediachain, tracking the mapping of canonicals to chain heads.

The next part will add the Journal Blockchain generation.

**Comment by vyzo** [comment]
Added Journal Blockchain generation.

**Comment by vyzo** [comment]
The implementation is reasonably complete; remains to be tested in the real world.

**Comment by vyzo** [comment]
initial work is done, closing.
