### ISSUE TITLE
Glossary [TODO]

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#29]
We have some inconsistent term usage again, let's nip that in the bud and establish definitions. I am particularly concerned about:

**canonical:** we've generally used this for the root ID but now we seem to also be using it for the multihash IPFS address of an object
**peer/client:** in the RFC we have Peers (~= transactors?) but usage seems to have shifted to peers meaning transactors + nodes accepting syndication + ???

@bigs @vyzo

**Comment by bigs** [comment]
yeah good call
- **transactors** - accept writes, maintain journal
- **clients** - accept syndicated values from transactors, are primary query interface for reads
- **canonical** - permanent identifier, points to root

**Comment by parkan** [comment]
**clients** could also read too, though, right? so read write or both, in theory

feel like there should be some distinct terms

**Comment by bigs** [comment]
well a **client** can read head from a transactor but don't support writes unless they open up a session to **transactors** specifically, which is outside of spec

**Comment by parkan** [comment]
@bigs do you mean supporting writes is outside the spec, or NOT supporting writes is? having trouble parsing that statement

my impression from our discussions was that the reader and writer client parts (which read HEAD/receive `journal-commit` events and send `put` commands, respectively) are logically somewhat separate

**Comment by bigs** [comment]
ah... transactors support writes, but clients do not by their specification. ultimately, a client is just an interface for receiving a stream of updates to the chain. programmers implementing clients may choose to accept and propagate writes on behalf of users

**Comment by parkan** [comment]
right, ok so then we need a different word for writers

**Comment by bigs** [comment]
@parkan client-clients :stuck_out_tongue: 

edit: or plebians

**Comment by parkan** [comment]
petitioners?

**Comment by bigs** [comment]
maybe writers / readers / transactors / clients

**Comment by parkan** [comment]
**folding:** producing a single flattened representation of a chain of updates, reconciling any conflicts and discarding bad information in the process

**Comment by parkan** [comment]
Added here: https://github.com/mediachain/mediachain/wiki/Glossary
