### ISSUE TITLE
pattern match in TypeSerialization.fromCMap not @switch optimizeable

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#46]
For unclear reasons, dispatching on `type` doesn't seem to give us a `tableswitch` even though the values are constant and final.

http://alvinalexander.com/scala/using-match-expression-like-switch-statement

http://stackoverflow.com/questions/16311540/why-cant-scala-optimize-this-match-to-a-switch/16318995#16318995

**Comment by yusefnapora** [comment]
closing this since we're using `Map`s instead of pattern matching now
