### ISSUE TITLE
Mediachain Data Submission Guidelines

### ISSUE THREAD

**Issue by denisnazarov** [mediachain/mediachain#49]
In order to submit your metadata to Mediachain, the following fields are recommended so your data to be indexed by the system:
- Attribution (Artist, Photographer, Author, etc.)
- Date (optional)
- Description (optional)
- Keywords (optional)
- License (optional, recommended)

Any other information you’re open to sharing is welcome, so we can gain insights on future interoperability and the kinds of indexes that should be created.

**For perceptual indexing (image recognition)**
- Image asset (file or url)
  - 300px in the smallest dimensions
  - Watermarks ok

**Format**
The following are preferred, but any machine-readable format is fine
- JSON (preferred) or CSV dump, as flat file or directory hierarchy
- API endpoint (include any necessary tokens/permissions)

If any tokens/permissions are private, feel free to contact one of the Mediachain devs here, via [email](mailto:hello@mediachain.io), or on [Slack](http://slack.mediachain.io).

**Comment by CromonMS** [comment]
Have you looked at DDEX, it's an attempt at metadata normalization.

http://www.ddex.net/ddex-standards

**Comment by parkan** [comment]
@CromonMS we feel that DDEX suffers a bit from the ["now there are 15 standards" problem](https://xkcd.com/927/). Our goal is to accept submissions in existing standards and write lightweight translators/extractors on top of them -- we'll probably build one for DDEX.

**Comment by CromonMS** [comment]
@parkan that's cool, was more wondering really, I'm not convinced myself either and feel the same as you re: the many standards. I need to read more of your documentation anyways, just wanted to throw something out there :)

**Comment by parkan** [comment]
@CromonMS totally, this is an open area of investigation for us too but I think the overall direction we're going in is more promising. I'll ping you when we have more tooling developed around this part of the system

**Comment by parkan** [comment]
More of a consideration for translator/we are the active receivers for now anyway, closing

**Comment by denisnazarov** [comment]
Go to apps to contribute to Mediachain! http://github.com/mediachain/apps
