### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by denisnazarov** [mediachain/mediachain#5]
High-level explanation of what Mediachain is.

Since this will be where people land before reading the RFCs, etc.

**Comment by denisnazarov** [comment]
@parkan Beyond covering above, thoughts on organizing the README?

We now have this, L-SPACE, and cli. If this repo's README is the entry-point to the project what is the current distinction between mediachain/mediachain mediachain/L-SPACE, etc.

**Comment by parkan** [comment]
We're still weeks away from the codebase really being useful to anybody else (or knowing how we want to orchestrate these services) so maybe just put a high-level summary in the readme for now? I am guessing eventually it'll be "download this docker image..."

**Comment by denisnazarov** [comment]
@yusefnapora lets add the diagram to the README when it's done

**Comment by parkan** [comment]
we should also really have the other diagram detailing the data structure in here as well -- I think that may go well with bigs' writeup

**Comment by denisnazarov** [comment]
Let close after we get the data structure diagram in.

**Comment by parkan** [comment]
Closing until relevant again
