### ISSUE TITLE
Client responsibilities

### ISSUE THREAD

**Issue by yusefnapora** [mediachain/mediachain#59]
I just wanted to write down my current understanding of the responsibilities of the "client".  By which I mean the process that connects to the transactor cluster and exposes an RPC interface to "supplicants" (or whatever we end up calling the lightweight clients that don't talk directly to the transactors).  Please let me know if I'm missing anything!

The client is responsible for:
- getting the current block from a transactor at init, to bootstrap the system
- responding to blockchain updates from the transactors & pulling new blocks, records, etc.
- fetching blocks from the datastore, beginning with the current block, and working back to the genesis block
- fetching the `CanonicalRecord`s and `ChainCell`s referenced in the journal blocks
- "folding" the chain of update cells into a consistent "view" of an object at a point in time.
  - "point in time" defaults to "now", but could potentially be "as of" any point in the past
    - can happen "on demand" in response to queries, and/or cached for future reference
- maintaining a local cache of the datastore for efficient query
  - technically optional, but probably necessary for performance
  - if the datastore is ipfs, could potentially use the local repo as a cache
  - first pass can use RocksDB datastore
- exposing an RPC interface for "supplicants"
  - Allows lightweight query of the system without participation in the blockchain update process
  - provides "folded" view of records
  - relays write requests to the transactors

**Comment by vyzo** [comment]
It doesn't necessarily need a cache of the datastore -- it can access the backing store directly.

**Comment by parkan** [comment]
I think we worked through this, pretty much
