### ISSUE TITLE
Verify transactor performance

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#85]
We're looking to import ~1MM records for a [pilot project](https://github.com/mediachain/mediachain/milestones/Getty%20import)

We should establish performance and stability characteristics of our test cluster in preparation. The generators from #83 can probably help generate the test data.

**Comment by vyzo** [comment]
I think we should make a performance suite that collects baseline measurements, and run it with multiple client-server configurations. 

I can do small scale testing on my laptop -- we can use a large ec2 instance for more.

**Comment by vyzo** [comment]
#89 implements basic testing client-server apps.
Running the single-stepping chain building test on my (not terribly fast) laptop yields 40s for 1000 writes and 195s for 5000 writes.

So ingesting 1M records at this pace would require 11hrs.

**Comment by vyzo** [comment]
Running two clients in parallel each doing 1000 writes gave 35-40s total time for both of them.
So there is a lot of room for performanace improvement.

**Comment by vyzo** [comment]
Added a concurrent write test, which shows the effect of parallelism in performance.
It takes 50s for 5000 writes with 5 concurrent chains and 65s for 10k writes with 10 concurrent chains.

**Comment by vyzo** [comment]
What these numbers indicate is that it should be possible to ingest 1M records in less than 2hrs.

**Comment by vyzo** [comment]
20k writes with 20 concurrent chains takes 1m26.142s, there is substantial room for performance with parallelism.

**Comment by vyzo** [comment]
100k writes with 100 concurrent chains takes 7m14.478s
I think this hits the parallelism limit on my laptop.

**Comment by vyzo** [comment]
the datastore write backlog takes an additional 10-15min to flush to the local dynamo db.

**Comment by parkan** [comment]
Perfect! These numbers are in the ballpark that we need
