### ISSUE TITLE
Ad-hoc ingest script

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#86]
A throwaway importer in lieu of full-fledged writer client. Approximately this:
- [x] preprocess dump, generate author -> pseudo-id mapping (deduplicate)
- [x] generate entity + insert
- [x] generate artefact cells + insert

**Comment by yusefnapora** [comment]
This is generating entity and artefact cells, and an ArtefactCreationCell, and inserting them into the dynamo store.  But we still need to wire it up to the transactor before we can switch it on 😄

**Comment by vyzo** [comment]
once the transactor is wired we shouldn't need to write to the store, the transactor writes for us.

**Comment by yusefnapora** [comment]
true, except for the raw metadata blobs, which we're writing to the store directly so we can link to them from inside the `meta` map.  I'm changing all the other writes to go through the transactor now.
