### ISSUE TITLE
Indexer template project

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#87]
Basic indexer skeleton that contains reader client/syndication receiver interface and a black box index/search implementation. To be used as base for Getty demo.

**Comment by parkan** [comment]
this is basically relatively thin shell around #70

**Comment by parkan** [comment]
@autoencoder how much work do you think it would be to split out the gRPC client + tornado server part so anyone can write their own indexer? Something that exposes a `journal_event_received` + `query` hooks to plug into, basically (maybe minus all the dedupe stuff etc even)

**Comment by autoencoder** [comment]
Been decoupling the tornado / search / storage parts a bit more, and should be ready with most of that in the next day or so. Think that will make what you're describing easy.

We should expose the API over gRPC too?

**Comment by parkan** [comment]
I would just push out what we have at the moment, but some bonus gRPC might be nice

**Comment by parkan** [comment]
Closing, but this is potentially worth revisiting later.
