### ISSUE TITLE
MVP indexer

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#90]
Based on #87, build an MVP indexer that we ourselves can run (may also be shipped as the OSS reference impl)

This may be a simple keyword search, for ex. https://github.com/mediachain/schema-translators/issues/4 has keyword metadata that we can ingest by following a reference edge

**Comment by autoencoder** [comment]
MVP Indexer now at [mediachain/mediachain-indexer](https://github.com/mediachain/mediachain-indexer) and described in [RFC-3](https://github.com/mediachain/mediachain/blob/master/rfc/mediachain-rfc-3.md). Contains reference implementation baselines for: content-based image search, text-based image search, and image dedupe.
